<?php

namespace Exo\MotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * motoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motoRepository extends EntityRepository
{
	public function getMotoWithCategorie()
	{
	    $jn = $this->createQueryBuilder('m')
               ->join('m.nom_categorie', 'c')
			   ->join('m.pieces', 'p')
               ->addSelect('c', 'p');

			return $jn->getQuery()
               ->getResult();
	}
}