<?php

namespace Exo\MotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceRepository extends EntityRepository
{
}